# Generated by Django 3.1.1 on 2020-09-28 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms_auth', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=100),
        ),
    ]
